const { faker } = require('@faker-js/faker');

function getFakeValue (fakePath) {
  switch (fakePath) {
    case '$guid':
      return faker.datatype.uuid();
      case '$timestamp':
        return parseInt(new Date().getTime()/1000);
      case '$isoTimestamp':
        return new Date().toISOString();
      case '$randomUUID':
        return faker.datatype.uuid();
      case '$randomAlphaNumeric':
        return faker.random.alphaNumeric()
      case '$randomBoolean':
        return Math.random() >= 0.5 ? true : false
      case '$randomInt':
        return parseInt(faker.random.numeric(3, {allowLeadingZeros: true}))
      case '$randomColor':
        return faker.color.human()
      case '$randomHexColor':
        return faker.color.rgb({ format: 'hex', casing: 'lower' })
      case '$randomAbbreviation':
        return faker.hacker.abbreviation()
      case '$randomIP':
        return faker.internet.ipv4()
      case '$randomIPV6':
        return faker.internet.ipv6()
      case '$randomMACAddress':
        return faker.internet.mac()
      case '$randomPassword':
        return faker.internet.password()
      case '$randomLocale':
        return faker.random.locale()
      case '$randomUserAgent':
        return faker.internet.userAgent()
      case '$randomProtocol':
        return faker.internet.protocol()
      case '$randomSemver':
        return faker.system.semver()
      case '$randomFirstName':
        return faker.name.firstName()
      case '$randomLastName':
        return faker.name.lastName()
      case '$randomFullName':
        return faker.name.fullName();
      case '$randomNamePrefix':
        return faker.name.prefix()
      case '$randomNameSuffix':
        return faker.name.suffix()
      case '$randomJobArea':
        return faker.name.jobArea()
      case '$randomJobDescriptor':
        return faker.name.jobDescriptor()
      case '$randomJobTitle':
        return faker.name.jobTitle()
      case '$randomJobType':
        return faker.name.jobType()
      case '$randomPhoneNumber':
        return faker.phone.number('###-###-####')
      case '$randomPhoneNumberExt':
        return faker.phone.number('##-###-###-####')
      case '$randomCity':
        return faker.address.city()
      case '$randomStreetName':
        return faker.address.street()
      case '$randomStreetAddress':
        return faker.address.streetAddress()
      case '$randomCountry':
        return faker.address.country()
      case '$randomCountryCode':
        return faker.address.countryCode()
      case '$randomLatitude':
        return faker.address.latitude()
      case '$randomLongitude':
        return faker.address.longitude()
      case '$randomAvatarImage':
        return faker.internet.avatar()
      case '$randomImageUrl':
        return faker.image.imageUrl()
      case '$randomAbstractImage':
        return faker.image.abstract()
      case '$randomAnimalsImage':
        return faker.image.animals() 
      case '$randomBusinessImage':
        return faker.image.business()
      case '$randomCatsImage':
        return faker.image.cats()
      case '$randomCityImage':
        return faker.image.city()
      case '$randomFoodImage':
        return faker.image.food()
      case '$randomNightlifeImage':
        return faker.image.nightlife()
      case '$randomFashionImage':
        return faker.image.fashion()
      case '$randomPeopleImage':
        return faker.image.people()
      case '$randomNatureImage':
        return faker.image.nature()
      case '$randomSportsImage':
        return faker.image.sports()
      case '$randomTransportImage':
        return faker.image.transport()
      case '$randomImageDataUri':
        return faker.image.dataUri()
      case '$randomBankAccount':
        return faker.finance.account() 
      case '$randomBankAccountName':
        return faker.finance.accountName()
      case '$randomCreditCardMask':
        return faker.finance.mask()
      case '$randomBankAccountBic':
        return faker.finance.bic()
      case '$randomBankAccountIban':
        return faker.finance.iban() 
      case '$randomTransactionType':
        return faker.finance.transactionType()
      case '$randomCurrencyCode':
        return faker.finance.currencyCode()
      case '$randomCurrencyName':
        return faker.finance.currencyName()
      case '$randomCurrencySymbol':
        return faker.finance.currencySymbol()
      case '$randomBitcoin':
        return faker.finance.bitcoinAddress()
      case '$randomCompanyName':
        return faker.company.name()
      case '$randomCompanySuffix':
        return faker.company.companySuffix()
      case '$randomBs':
        return faker.company.bs()
      case '$randomBsAdjective':
        return faker.company.bsAdjective()
      case '$randomBsBuzz':
        return faker.company.bsBuzz()
      case '$randomBsNoun':
        return faker.company.bsNoun()
      case '$randomCatchPhrase':
        return faker.company.catchPhrase()
      case '$randomCatchPhraseAdjective':
        return faker.company.catchPhraseAdjective()
      case '$randomCatchPhraseDescriptor':
        return faker.company.catchPhraseDescriptor()
      case '$randomCatchPhraseNoun':
        return faker.company.catchPhraseNoun()
      case '$randomDatabaseColumn':
        return faker.database.column()
      case '$randomDatabaseType':
        return faker.database.type()
      case '$randomDatabaseCollation':
        return faker.database.collation()
      case '$randomDatabaseEngine':
        return faker.database.engine()
      case '$randomDateFuture':
        return faker.date.future()
      case '$randomDatePast':
        return faker.date.past()
      case '$randomDateRecent':
        return faker.date.recent()
      case '$randomWeekday':
        return faker.date.weekday()
      case '$randomMonth':
        return faker.date.month()
      case '$randomDomainName':
        return faker.internet.domainName()
      case '$randomDomainSuffix':
        return faker.internet.domainSuffix()
      case '$randomDomainWord':
        return faker.internet.domainWord()
      case '$randomEmail':
        return faker.internet.email()
      case '$randomExampleEmail':
        return faker.internet.exampleEmail()
      case '$randomUserName':
        return faker.internet.userName()
      case '$randomUrl':
        return faker.internet.url()
      case '$randomFileName':
        return faker.system.commonFileName()
      case '$randomFileType':
        return faker.system.commonFileType()
      case '$randomFileExt':
        return faker.system.fileExt()
      case '$randomCommonFileName':
        return faker.system.commonFileName()
      case '$randomCommonFileType':
        return faker.system.commonFileType()
      case '$randomCommonFileExt':
        return faker.system.fileExt()
      case '$randomFilePath':
        return faker.system.filePath()
      case '$randomDirectoryPath':
        return faker.system.directoryPath()
      case '$randomMimeType':
        return faker.system.mimeType()
      case '$randomPrice':
        return faker.commerce.price()
      case '$randomProduct':
        return faker.commerce.product()
      case '$randomProductAdjective':
        return faker.commerce.productAdjective()
      case '$randomProductDescription':
        return faker.commerce.productDescription()
      case '$randomProductMaterial':
        return faker.commerce.productMaterial()
      case '$randomProductName':
        return faker.commerce.productName()
      case '$randomDepartment':
        return faker.commerce.department()
      case '$randomNoun':
        return faker.word.noun()
      case '$randomVerb':
        return faker.word.verb()
      case '$randomIngverb':
        return faker.hacker.ingverb()
      case '$randomAdjective':
        return faker.word.adjective()
      case '$randomWord':
        return faker.random.word()
      case '$randomWords':
        return faker.random.words()
      case '$randomPhrase':
        return faker.hacker.phrase()
      case '$randomLoremWord':
        return faker.lorem.word()
      case '$randomLoremWords':
        return faker.lorem.words()
      case '$randomLoremSentence':
        return faker.lorem.sentence()
      case '$randomLoremSentences':
        return faker.lorem.sentences()
      case '$randomLoremParagraph':
        return faker.lorem.paragraph()
      case '$randomLoremParagraphs':
        return faker.lorem.paragraphs(Math.ceil(Math.random() * 5),'\\n')
      case '$randomLoremText':
        return faker.lorem.text()
      case '$randomLoremSlug':
        return faker.lorem.slug()
      case '$randomLoremLines':
        return faker.lorem.paragraphs(1,'\\n')
    default:
      return null
  }
}

module.exports = {
  getFakeValue: getFakeValue
}